"use strict";
/* Page generale uniquement : aucune sous-page, aucun envoi de formulaire. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const OUT=path.join(process.cwd(),'dist'),BASE='https://www.mecenia.org';
const read=p=>fs.readFileSync(path.join(OUT,p),'utf8');
const put=(p,h)=>{const f=path.join(OUT,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,h)};
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const main=h=>(h.match(/<main\b[^>]*>[\s\S]*?<\/main>/)||[''])[0];
const template=read('a-propos/index.html'),aboutBefore=main(template),contactBefore=read('contact/index.html');
const forms=h=>[...h.matchAll(/<form\b[^>]*>[\s\S]*?<\/form>/gi)].map(m=>m[0]);
const offers=[
['Accompagnement','Clarifier les besoins, les objectifs et les contraintes du projet.','Note de cadrage et feuille de route adaptée.'],
['Prospection de mécènes','Identifier les interlocuteurs, hiérarchiser les pistes et préparer les outils de contact.','Cartographie, liste priorisée, argumentaire et plan de prise de contact.'],
['Dossier de mécénat','Présenter le projet, ses publics, ses besoins et ce que le soutien peut rendre possible.','Dossier de présentation, budget et supports de discussion.'],
['Plan de communication','Rendre le projet lisible auprès des partenaires et des publics.','Messages par cible, choix des supports et calendrier de communication.'],
['Modèle économique','Organiser les ressources et les charges pour éclairer les choix du projet.','Budget prévisionnel, scénarios de financement et plan d’action.'],
['Dossier de subvention','Identifier les dispositifs pertinents et préparer les éléments administratifs de candidature.','Organisation des pièces, dossier et calendrier de dépôt.']
];
const contactLink=s=>'/contact/?mecenia_service='+encodeURIComponent(s);
const body=`<section class="hero small"><div class="container hero-content"><div class="breadcrumb rise"><a href="/">Accueil</a> &nbsp;/&nbsp; Aide au mécénat</div><h1 class="rise d1">Aide au mécénat</h1><p class="sub rise d2">Donner à votre projet culturel les moyens de rencontrer ses soutiens.</p><div class="btn-row rise d3"><a class="btn" href="${contactLink('Accompagnement')}">Présenter mon projet</a></div></div></section>
<section class="bg-white" id="accompagnement"><div class="container"><span class="eyebrow reveal">Notre accompagnement</span><h2 class="title reveal">Une démarche adaptée à votre projet</h2><p class="lead reveal">Mecenia accompagne les institutions culturelles et les artistes dans la préparation de leur recherche de financement, et les entreprises dans la construction de leur engagement culturel.</p><div class="grid g2 stagger"><article class="card"><h3>Institutions et artistes</h3><p>Clarifier le besoin, présenter le projet et préparer une recherche de partenaires cohérente avec vos publics, votre budget et votre calendrier.</p></article><article class="card"><h3>Entreprises</h3><p>Préciser vos objectifs d’engagement, comprendre les projets culturels et préparer une relation de partenariat adaptée à vos priorités.</p></article></div></div></section>
<section class="bg-beige" id="prestations"><div class="container"><span class="eyebrow reveal">Nos prestations</span><h2 class="title reveal">Des outils concrets pour avancer</h2><p class="lead reveal">Les interventions peuvent être mobilisées séparément ou réunies dans une mission. Leur périmètre et leurs livrables sont définis après échange.</p><div class="grid g3 stagger">${offers.map(([name,goal,deliverable])=>'<article class="card"><h3>'+esc(name)+'</h3><p>'+esc(goal)+'</p><p><strong>Livrables possibles :</strong> '+esc(deliverable)+'</p><a class="arrow-link" href="'+contactLink(name)+'">Échanger sur cette mission</a></article>').join('')}</div></div></section>
<section class="bg-white" id="prospection"><div class="container narrow"><div class="prose reveal"><span class="eyebrow" style="text-align:left">Une prospection ciblée</span><h2>Privilégier les bons interlocuteurs</h2><p>Notre prospection repose d’abord sur l’identification des interlocuteurs, la priorisation et la préparation des outils de contact. Elle privilégie une démarche ciblée plutôt qu’une campagne massive d’appels à froid.</p><p>Lorsque cela est pertinent et possible, des mises en relation et un suivi ponctuel peuvent compléter la mission, notamment en mobilisant les contacts accessibles à Mecenia. Leur contenu est précisé avant engagement.</p><p>Aucune collecte ni décision de financement n’est garantie : chaque partenaire demeure libre de son engagement.</p></div></div></section>
<section class="bg-beige" id="demarche"><div class="container narrow"><span class="eyebrow reveal">Comment commencer</span><h2 class="title reveal">Un échange, puis une mission cadrée</h2><ol class="steps reveal"><li><b>Présenter votre besoin</b>Votre projet, votre objectif, vos contraintes et les moyens disponibles.</li><li><b>Définir l’intervention</b>Un périmètre, des livrables, un calendrier et des conditions financières convenus avant lancement.</li><li><b>Avancer et restituer</b>Des outils utilisables, un point de restitution et les suites adaptées à votre projet.</li></ol><p class="note reveal">Chaque demande est étudiée selon les besoins et les disponibilités. Aucun tarif standard n’est annoncé sur cette page.</p></div></section>
<section class="bg-white" id="cadre"><div class="container narrow"><div class="prose reveal"><h2>Un périmètre clair</h2><p>L’accompagnement porte sur la stratégie, la communication et la préparation opérationnelle des dossiers. L’information générale sur le mécénat ne vaut pas consultation juridique ou fiscale personnalisée, rédaction d’actes juridiques ou validation de l’éligibilité d’un don.</p><p>Les questions qui nécessitent une habilitation sont traitées par des professionnels autorisés. Aucun avantage fiscal, subvention ou financement n’est promis.</p></div></div></section>
<section class="bg-dark cta"><div class="container reveal"><h2>Parlons de votre projet culturel</h2><p>Un besoin précis ou une démarche à construire : décrivez-nous votre situation.</p><a class="btn" href="${contactLink('Accompagnement')}">Contacter Mecenia</a></div></section>`;
let h=template;const title='Aide au mécénat — Accompagnement et prestations | Mecenia',description='Accompagnement au mécénat, prospection ciblée, communication et dossiers de financement : une mission définie selon votre projet, sans résultat garanti.';
h=h.replace(/<main\b[^>]*>[\s\S]*?<\/main>/,()=>'<main id="contenu">'+body+'</main>').replace(/<title>[\s\S]*?<\/title>/,()=>'<title>'+esc(title)+'</title>').replace(/<link rel="canonical" href="[^"]*"[^>]*>/,()=>'<link rel="canonical" href="'+BASE+'/aide-au-mecenat/">');
h=h.replace(/<meta\b[^>]*(?:name|property)="(description|og:title|og:description|og:url|twitter:title|twitter:description)"[^>]*>/g,(_,k)=>'<meta '+(k.startsWith('og:')?'property':'name')+'="'+k+'" content="'+esc(k.endsWith('title')?title:k==='og:url'?BASE+'/aide-au-mecenat/':description)+'">');
const ld={'@context':'https://schema.org','@graph':[{'@type':'NGO','@id':BASE+'/#organization',name:'Mecenia',url:BASE+'/'},{'@type':'WebPage',url:BASE+'/aide-au-mecenat/',name:title,description,inLanguage:'fr-FR'}]};
h=h.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/g,()=>'<script type="application/ld+json">'+JSON.stringify(ld).replace(/</g,'\u003c')+'</script>');put('aide-au-mecenat/index.html',h);
function addLink(block){if(block.includes('href="/aide-au-mecenat/"'))return block;return block.replace(/(<li\b[^>]*>\s*<a\b[^>]*href="\/a-propos\/"[^>]*>[\s\S]*?<\/a>\s*<\/li>)/,'$1<li><a href="/aide-au-mecenat/">Aide au mécénat</a></li>')}
function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory()){if(!['admin','assets','netlify'].includes(e.name))walk(f)}else if(e.name.endsWith('.html')){let s=fs.readFileSync(f,'utf8');s=s.replace(/<nav\b[^>]*>[\s\S]*?<\/nav>/g,addLink).replace(/<footer\b[^>]*>[\s\S]*?<\/footer>/g,addLink);fs.writeFileSync(f,s)}}}walk(OUT);
const prefill=`<script id="mecenia-aide-prefill">(function(){var service=new URLSearchParams(location.search).get('mecenia_service');if(${JSON.stringify(offers.map(o=>o[0]))}.indexOf(service)===-1)return;var f=document.querySelector('form[name="contact"]');if(!f)return;var m=f.querySelector('[name="message"]');if(!m||m.value.trim())return;m.value='Bonjour, je souhaite échanger avec Mecenia au sujet de la mission : '+service+'.';var s=f.querySelector('[name="sujet"]');if(s){var o=[].slice.call(s.options).find(function(x){return x.value==='Partenariat'||x.value==='Autre'});if(o)s.value=o.value}})();</script>`;
let contact=read('contact/index.html');if(!contact.includes('id="mecenia-aide-prefill"'))contact=contact.replace('</body>',()=>prefill+'\n</body>');put('contact/index.html',contact);
assert(main(read('a-propos/index.html'))===aboutBefore,'Le texte À propos a été modifié');
assert(JSON.stringify(forms(contact))===JSON.stringify(forms(contactBefore)),'Les formulaires ont été modifiés');
const result=read('aide-au-mecenat/index.html'),ids=[...result.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert(ids.length===new Set(ids).size,'Identifiants dupliqués sur Aide au mécénat');
assert(result.includes('href="/aide-au-mecenat/"'),'Lien de navigation absent');
const sm=path.join(OUT,'sitemap.xml');if(fs.existsSync(sm)){let s=fs.readFileSync(sm,'utf8');if(!s.includes('<loc>'+BASE+'/aide-au-mecenat/</loc>'))s=s.replace('</urlset>','<url><loc>'+BASE+'/aide-au-mecenat/</loc><lastmod>2026-10-08</lastmod></url>\n</urlset>');fs.writeFileSync(sm,s)}
const lm=path.join(OUT,'llms.txt');if(fs.existsSync(lm)){let s=fs.readFileSync(lm,'utf8');if(!s.includes(BASE+'/aide-au-mecenat/'))s+='\n- [Aide au mécénat]('+BASE+'/aide-au-mecenat/) : accompagnement et prestations, mission définie après échange.\n';fs.writeFileSync(lm,s)}
console.log('Aide au mécénat : page générale ajoutée, À propos et champs de formulaire conservés.');
