"use strict";
/* Page generale des evenements : aucun evenement date ni inscription automatique. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const OUT=path.join(process.cwd(),'dist'),BASE='https://www.mecenia.org';
const read=p=>fs.readFileSync(path.join(OUT,p),'utf8');
const put=(p,h)=>{const f=path.join(OUT,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,h)};
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const main=h=>(h.match(/<main\b[^>]*>[\s\S]*?<\/main>/)||[''])[0];
const template=read('a-propos/index.html'),beforeAbout=main(template),beforeAide=main(read('aide-au-mecenat/index.html')),beforeContact=read('contact/index.html');
const forms=h=>[...h.matchAll(/<form\b[^>]*>[\s\S]*?<\/form>/gi)].map(m=>m[0]);
const request=c=>'/contact/?mecenia_evenement='+encodeURIComponent(c);
const body=`<section class="hero small"><div class="container hero-content"><div class="breadcrumb rise"><a href="/">Accueil</a> &nbsp;/&nbsp; Événements</div><h1 class="rise d1">Événements</h1><p class="sub rise d2">Faire se rencontrer les idées, les projets et leurs futurs partenaires.</p><div class="btn-row rise d3"><a class="btn" href="#formats">Découvrir les formats</a></div></div></section>
<section class="bg-white" id="rencontres"><div class="container narrow"><div class="prose reveal"><span class="eyebrow" style="text-align:left">La rencontre au service des projets</span><h2>Partager les pratiques, ouvrir le dialogue</h2><p>Les événements de Mecenia réunissent les institutions culturelles, les artistes, les acteurs publics et les entreprises pour comprendre les besoins, partager les expériences et encourager les collaborations.</p><p>Chaque format poursuit une même finalité : permettre aux mondes culturel et économique de mieux se connaître, puis de travailler sur des sujets et des projets concrets. La rencontre crée des occasions de dialogue ; elle ne garantit pas un partenariat ou un financement.</p></div></div></section>
<section class="bg-beige" id="formats"><div class="container"><span class="eyebrow reveal">Trois formats complémentaires</span><h2 class="title reveal">RCA, colloques et webinaires</h2><div class="grid g3 stagger"><article class="card"><h3>Rencontres de la Culture et des Affaires</h3><p>Le rendez-vous annuel porté par Mecenia pour rapprocher institutions, acteurs publics et entreprises autour des projets culturels et du mécénat.</p><a class="arrow-link" href="#rca">Découvrir les RCA</a></article><article class="card"><h3>Colloques</h3><p>Des échanges approfondis sur un enjeu culturel, économique ou de financement, associant des points de vue complémentaires et des retours d’expérience.</p><a class="arrow-link" href="${request('colloque')}">Demander des informations</a></article><article class="card"><h3>Webinaires</h3><p>Des rencontres en ligne, ciblées et accessibles, pour partager des repères, découvrir des pratiques et ouvrir la discussion autour d’un sujet.</p><a class="arrow-link" href="${request('webinaire')}">Demander des informations</a></article></div></div></section>
<section class="bg-white" id="rca"><div class="container"><div class="split"><div class="reveal"><img class="rca-logo" src="/assets/img/logo-rca.png" width="560" height="569" loading="lazy" alt="Rencontres de la Culture et des Affaires"></div><div class="prose reveal"><span class="eyebrow" style="text-align:left">Notre rendez-vous annuel</span><h2>Les RCA : rapprocher les regards et les projets</h2><p>Les Rencontres de la Culture et des Affaires ont vocation à réunir ceux qui portent les projets culturels et ceux qui souhaitent les soutenir. Échanges thématiques, expériences partagées et rencontres entre acteurs nourrissent cette ambition.</p><p>La programmation se construit progressivement. Le lieu, la date, les intervenants et les modalités de participation seront annoncés lorsqu’ils seront confirmés.</p><p><a class="arrow-link" href="${request('rca')}">Être informé des prochaines annonces</a></p></div></div></div></section>
<section class="bg-beige" id="programmation"><div class="container narrow"><span class="eyebrow reveal">Programmation</span><h2 class="title reveal">Une programmation en préparation</h2><p class="lead reveal">Aucun événement daté ni inscription ouverte n’est annoncé sur cette page pour le moment.</p><div class="prose reveal"><p>Chaque annonce précisera le sujet, la date, le lieu ou le format en ligne, ainsi que les modalités de participation. Les informations confirmées seront publiées ici.</p><p>En attendant, vous pouvez nous faire part de votre intérêt ou proposer une contribution. Une demande d’information ne vaut ni réservation ni inscription confirmée.</p></div></div></section>
<section class="bg-white" id="contribuer"><div class="container"><span class="eyebrow reveal">Contribuer à la rencontre</span><h2 class="title reveal">Trois façons de vous associer</h2><div class="grid g3 stagger"><article class="card"><h3>Proposer une intervention</h3><p>Une expérience, un sujet ou un projet à partager avec les acteurs culturels et économiques ? Présentez-nous votre proposition.</p><a class="arrow-link" href="${request('intervention')}">Proposer une intervention</a></article><article class="card"><h3>Accueillir une rencontre</h3><p>Institution, entreprise ou lieu culturel : échangeons sur l’accueil d’un colloque ou d’un temps de dialogue adapté au sujet et aux publics.</p><a class="arrow-link" href="${request('accueil')}">Proposer un accueil</a></article><article class="card"><h3>Envisager un partenariat</h3><p>Associer votre structure à un événement, apporter des compétences ou des moyens : discutons du cadre et des engagements possibles.</p><a class="arrow-link" href="${request('partenariat')}">Échanger sur un partenariat</a></article></div></div></section>
<section class="bg-dark cta"><div class="container reveal"><h2>Une idée de rencontre à construire ensemble ?</h2><p>Écrivez-nous pour partager un sujet, proposer votre participation ou demander des informations.</p><a class="btn" href="${request('intervention')}">Contacter Mecenia</a></div></section>`;
let h=template;const title='Événements — RCA, colloques et webinaires | Mecenia',description='Les événements de Mecenia : Rencontres de la Culture et des Affaires, colloques et webinaires. Programmation en préparation et propositions de contribution.';
h=h.replace(/<main\b[^>]*>[\s\S]*?<\/main>/,()=>'<main id="contenu">'+body+'</main>').replace(/<title>[\s\S]*?<\/title>/,()=>'<title>'+esc(title)+'</title>').replace(/<link rel="canonical" href="[^"]*"[^>]*>/,()=>'<link rel="canonical" href="'+BASE+'/evenements/">');
h=h.replace(/<meta\b[^>]*(?:name|property)="(description|og:title|og:description|og:url|twitter:title|twitter:description)"[^>]*>/g,(_,k)=>'<meta '+(k.startsWith('og:')?'property':'name')+'="'+k+'" content="'+esc(k.endsWith('title')?title:k==='og:url'?BASE+'/evenements/':description)+'">');
const ld={'@context':'https://schema.org','@graph':[{'@type':'NGO','@id':BASE+'/#organization',name:'Mecenia',url:BASE+'/'},{'@type':'WebPage',url:BASE+'/evenements/',name:title,description,inLanguage:'fr-FR'}]};
h=h.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/g,()=>'<script type="application/ld+json">'+JSON.stringify(ld).replace(/</g,'\u003c')+'</script>');put('evenements/index.html',h);
function addLink(block){if(block.includes('href="/evenements/"'))return block;return block.replace(/(<li\b[^>]*>\s*<a\b[^>]*href="\/aide-au-mecenat\/"[^>]*>[\s\S]*?<\/a>\s*<\/li>)/,'$1<li><a href="/evenements/">Événements</a></li>')}
function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory()){if(!['admin','assets','netlify'].includes(e.name))walk(f)}else if(e.name.endsWith('.html')){let s=fs.readFileSync(f,'utf8');s=s.replace(/<nav\b[^>]*>[\s\S]*?<\/nav>/g,addLink).replace(/<footer\b[^>]*>[\s\S]*?<\/footer>/g,addLink);fs.writeFileSync(f,s)}}}walk(OUT);
const messages={rca:'recevoir des informations sur les prochaines Rencontres de la Culture et des Affaires',colloque:'recevoir des informations sur les prochains colloques',webinaire:'recevoir des informations sur les prochains webinaires',intervention:'proposer une intervention ou un sujet pour un événement',accueil:'proposer un lieu pour accueillir une rencontre',partenariat:'échanger sur un partenariat autour des événements'};
const prefill=`<script id="mecenia-events-prefill">(function(){var code=new URLSearchParams(location.search).get('mecenia_evenement'),messages=${JSON.stringify(messages)};if(!Object.prototype.hasOwnProperty.call(messages,code))return;var f=document.querySelector('form[name="contact"]');if(!f)return;var m=f.querySelector('[name="message"]');if(!m||m.value.trim())return;m.value='Bonjour, je souhaite '+messages[code]+'.';var s=f.querySelector('[name="sujet"]');if(s){var options=[].slice.call(s.options),o=code==='partenariat'?options.find(function(x){return x.value==='Partenariat'}):options.find(function(x){return /intervention|événement/i.test(x.value)});if(!o)o=options.find(function(x){return x.value==='Autre'});if(o)s.value=o.value}})();</script>`;
let contact=read('contact/index.html');if(!contact.includes('id="mecenia-events-prefill"'))contact=contact.replace('</body>',()=>prefill+'\n</body>');put('contact/index.html',contact);
assert(main(read('a-propos/index.html'))===beforeAbout,'À propos modifié');assert(main(read('aide-au-mecenat/index.html'))===beforeAide,'Aide au mécénat modifié');assert(JSON.stringify(forms(contact))===JSON.stringify(forms(beforeContact)),'Champs de formulaire modifiés');
const result=read('evenements/index.html'),ids=[...result.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert(ids.length===new Set(ids).size,'Identifiants dupliqués sur Événements');assert(result.includes('href="/evenements/"'),'Lien de navigation absent');
for(const id of ['rencontres','formats','rca','programmation','contribuer'])assert(ids.includes(id),'Section absente : '+id);
const sm=path.join(OUT,'sitemap.xml');if(fs.existsSync(sm)){let s=fs.readFileSync(sm,'utf8');if(!s.includes('<loc>'+BASE+'/evenements/</loc>'))s=s.replace('</urlset>','<url><loc>'+BASE+'/evenements/</loc><lastmod>2026-10-08</lastmod></url>\n</urlset>');fs.writeFileSync(sm,s)}
const lm=path.join(OUT,'llms.txt');if(fs.existsSync(lm)){let s=fs.readFileSync(lm,'utf8');if(!s.includes(BASE+'/evenements/'))s+='\n- [Événements]('+BASE+'/evenements/) : RCA, colloques et webinaires ; programmation en préparation.\n';fs.writeFileSync(lm,s)}
console.log('Événements : page générale ajoutée, programmation en préparation, autres contenus et formulaires conservés.');
