"use strict";
const fs=require('node:fs'),path=require('node:path');
const names={tibre:'Sculpture of Tiber river (Louvre).jpg',tibere:'Tiberius Capri Louvre Ma1248.jpg',frise:'Frieze Magnesia ad Meandrum 32 Louvre.jpg',diane:'Artemisa Diane Versailles.jpg',venus:'Venus of Arles Louvre Ma439 n01.jpg',saisons:'Seasons mosaics, Ma 3444 (688).jpg'};
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plain=v=>String(v||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').trim();
const project='https://tousmecenes.louvre.fr/fr/projet/';
const clean=h=>h.replace(/Association loi 1901 en cours de formation\./g,'Association loi 1901.').replace(/basée à Paris \(en cours de formation\)/g,'basée à Paris');
const link=(u,t)=>{if(!/^https:\/\//.test(u||''))throw Error('Source invalide : '+u);return `<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(t)}</a>`};
const css=`<style id="mecenia-exposition-css">
.expo-page .expo-intro,.expo-page .expo-method{max-width:820px;margin:auto}.expo-page p{text-align:justify;hyphens:auto;text-wrap:pretty;margin-bottom:18px}.expo-page .hero p,.expo-page .cta p{text-align:center}.expo-page [id]{scroll-margin-top:110px}.expo-page h2{font-size:clamp(26px,3.8vw,38px);margin-bottom:22px}.expo-page h3{font-size:27px;margin:12px 0 20px}.expo-page h4{font-size:19px;margin-bottom:12px}.expo-page .expo-note,.expo-page .expo-reading{background:var(--beige);border-left:3px solid var(--caramel);padding:24px;border-radius:10px;margin:24px 0}.expo-page .expo-index{display:flex;flex-wrap:wrap;justify-content:center;gap:12px;margin-top:32px}.expo-page .expo-index a{border:1px solid var(--line);padding:10px 16px;border-radius:24px;font-size:13px}.expo-page .expo-act{max-width:760px;margin:0 auto 38px;text-align:center}.expo-page .expo-works{display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:start}.expo-page .expo-work{background:var(--white);border:1px solid var(--line);border-radius:12px;overflow:hidden;box-shadow:0 12px 32px #2e21140a}.expo-page .expo-figure{background:var(--offwhite)}.expo-page .expo-figure img{width:100%;height:350px;object-fit:contain;padding:20px}.expo-page figcaption,.expo-page .expo-sources{font-size:12px;color:var(--gray);padding:16px;border-top:1px solid var(--line)}.expo-page figcaption a,.expo-page .expo-sources a{text-decoration:underline;color:var(--caramel-dark)}.expo-page .expo-body{padding:28px}.expo-page .expo-number{font-size:11px;letter-spacing:2px;color:var(--bronze)}.expo-page .expo-status{display:inline-block;font-size:11px;padding:6px 10px;background:var(--beige);border:1px solid var(--line);border-radius:20px;margin-bottom:18px}.expo-page .editorial{border-style:dashed}.expo-page .expo-meta{display:grid;grid-template-columns:1fr 1fr;gap:16px;border-block:1px solid var(--line);padding:18px 0;margin-bottom:20px;font-size:13px}.expo-page dt{font-size:11px;color:var(--bronze);margin-bottom:4px}.expo-page dd{margin:0}.expo-page .expo-body p{font-size:15px}.expo-page summary{cursor:pointer;color:var(--caramel-dark);padding:16px 0;font-size:14px;min-height:44px}.expo-page details{border-top:1px solid var(--line)}.expo-page .expo-transition{font-style:italic;color:var(--gray)}.expo-page .expo-method ul{padding-left:20px}.expo-page .expo-method li{margin-bottom:12px}.expo-page .expo-source-date{font-size:12px;color:var(--gray)}
@media(max-width:860px){.expo-page .expo-works{grid-template-columns:1fr}.expo-page .expo-figure img{height:320px}.expo-page .expo-body{padding:24px}}@media(max-width:420px){.expo-page .expo-meta{grid-template-columns:1fr}.expo-page .expo-figure img{height:280px}.expo-page .expo-body{padding:20px}}
</style>`;
const extra={tibre:'La rame et la corne d’abondance associent le fleuve à la navigation et aux richesses de Rome. Selon le Louvre, cette statue en marbre du mont Pentélique ornait une fontaine du temple d’Isis à Rome, en pendant d’une statue du Nil ; découverte en 1512, elle rejoint le Louvre en 1797.',frise:'Le Louvre conserve quarante et une plaques, soit 42 % de cette frise du IIe siècle avant notre ère. L’amazonomachie met en scène des Amazones affrontant des héros, dont Héraclès. La photographie montre un détail de l’ensemble, non la totalité du décor.',saisons:'Découvert en 1935, ce pavement de villa romaine associe des allégories féminines ailées des saisons à des scènes de chasse et à des végétaux autour d’un bassin. Le Louvre décrit des tesselles de marbre, de pierre, de verre et de verre doré, dont la restauration de 2018–2019 a révélé la richesse. Cette photographie d’un état de présentation antérieur ne préfigure pas le nouvel accrochage.'};
module.exports=async function refresh(options={}){
 const root=options.root||process.cwd(),dist=path.join(root,'dist'),get=options.fetcher||globalThis.fetch;
 if(!get)throw Error('Node.js 18 ou supérieur requis.');
 const source=fs.readFileSync(path.join(root,'exposition/index.html'),'utf8'),match=source.match(/<script[^>]*id=["']expo-data["'][^>]*>([\s\S]*?)<\/script>/i);
 if(!match)throw Error('Données expo-data introuvables.');
 const data=JSON.parse(match[1]);
 if(data.works.length!==6||data.acts.length!==3||data.works.some(w=>!names[w.id]))throw Error('Structure de l’exposition inattendue.');
 const home=clean(fs.readFileSync(path.join(dist,'index.html'),'utf8')),header=home.match(/<header\b[\s\S]*?<\/header>/i),footer=home.match(/<footer\b[\s\S]*?<\/footer>/i);
 if(!header||!footer)throw Error('Écrin commun introuvable.');
 const head=home.match(/<head\b[^>]*>([\s\S]*?)<\/head>/i)[1],styles=(head.match(/<link\b[^>]*rel=["']stylesheet["'][^>]*>|<style\b[^>]*>[\s\S]*?<\/style>/gi)||[]).join('\n');
 const imageDir=path.join(dist,'assets/img/exposition');fs.mkdirSync(imageDir,{recursive:true});
 const manifestPath=path.join(imageDir,'credits.json');let manifest=fs.existsSync(manifestPath)?JSON.parse(fs.readFileSync(manifestPath,'utf8')):{};
 async function request(url){let error;for(let i=0;i<3;i++){try{const r=await get(url,{headers:{'User-Agent':'MeceniaSite/1.0 (https://mecenia.org; contact@mecenia.org)'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('HTTP '+r.status+' : '+url);return r}catch(e){error=e;if(i<2)await(options.wait||(ms=>new Promise(r=>setTimeout(r,ms))))(1500*(i+1))}}throw error}
 const missing=data.works.filter(w=>!manifest[w.id]||!fs.existsSync(path.join(imageDir,w.id+'.jpg')));
 if(missing.length){const query=new URLSearchParams({action:'query',format:'json',redirects:'1',prop:'imageinfo',iiprop:'url|extmetadata|mime',titles:missing.map(w=>'File:'+names[w.id]).join('|')}),payload=await(await request('https://commons.wikimedia.org/w/api.php?'+query)).json();if(payload.error)throw Error('Commons : '+payload.error.info);const pages=Object.values(payload.query&&payload.query.pages||{});
  for(const w of missing){const title='File:'+names[w.id],redirect=(payload.query.redirects||[]).find(r=>r.from===title),page=pages.find(p=>p.title===(redirect?redirect.to:title)),info=page&&page.imageinfo&&page.imageinfo[0];
   if(!info||info.mime!=='image/jpeg'||!/^https:\/\/upload\.wikimedia\.org\//.test(info.url))throw Error('Reproduction introuvable : '+title);
   const meta=info.extmetadata||{},value=k=>plain(meta[k]&&meta[k].value),artist=value('Artist'),license=value('LicenseShortName'),licenseUrl=value('LicenseUrl');
   if(!artist||!license||(licenseUrl&&!/^https:\/\//.test(licenseUrl)))throw Error('Crédits ou licence incomplets : '+title);
   const buffer=Buffer.from(await(await request(info.url)).arrayBuffer());if(buffer.length<1000||buffer[0]!==255||buffer[1]!==216)throw Error('JPEG invalide : '+title);
   fs.writeFileSync(path.join(imageDir,w.id+'.jpg'),buffer);manifest[w.id]={file:names[w.id],artist,license,licenseUrl,source:info.descriptionurl||'https://commons.wikimedia.org/wiki/'+encodeURIComponent(title),image:info.url};
  }fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');
 }
 function work(w,index){const m=manifest[w.id],editorial=w.status.includes('Mecenia'),credit=`${esc(m.artist)} · ${m.licenseUrl?link(m.licenseUrl,m.license):esc(m.license)} · ${link(m.source,'Photographie source')} · Affichage intégral, sans recadrage.`;
 return `<article class="expo-work" id="oeuvre-${esc(w.id)}"><figure class="expo-figure"><a href="/assets/img/exposition/${w.id}.jpg" target="_blank" rel="noopener" aria-label="Voir ${esc(w.title)} en grand"><img src="/assets/img/exposition/${w.id}.jpg" alt="${esc(w.alt)}" loading="lazy" decoding="async"></a><figcaption>${credit}</figcaption></figure><div class="expo-body"><span class="expo-number">Œuvre ${String(index+1).padStart(2,'0')}</span><h3>${esc(w.title)}</h3><span class="expo-status${editorial?' editorial':''}">${esc(w.status)}</span><dl class="expo-meta"><div><dt>Datation</dt><dd>${esc(w.date)}</dd></div><div><dt>Technique / inventaire</dt><dd>${esc(w.medium)}</dd></div><div><dt>Origine</dt><dd>${esc(w.origin)}</dd></div><div><dt>Collection</dt><dd>Musée du Louvre</dd></div></dl><p>${esc(w.notice)}</p>${extra[w.id]?`<p>${esc(extra[w.id])} ${link(project,'Présentation du Louvre')}</p>`:''}<details><summary>Lire le regard de Mecenia et les sources</summary><div class="expo-reading"><h4>Le regard de Mecenia</h4><p>${esc(w.reading)}</p></div><p class="expo-transition">${esc(w.transition)}</p><div class="expo-sources">${link(w.source,'Consulter la source institutionnelle')}<p>${editorial?'Contrepoint choisi par Mecenia ; aucun déplacement dans la cour n’est annoncé.':'Ensemble présenté dans le projet du Louvre ; cette exposition ne constitue pas un plan d’accrochage.'}</p></div></details></div></article>`}
 const acts=data.acts.map(act=>`<section class="${act.n===2?'bg-beige':'bg-white'}" id="etape-${act.n}"><div class="container"><div class="expo-act"><span class="eyebrow">Étape ${act.n} / 3</span><h2>${esc(act.title)}</h2><p>${esc(act.text)}</p></div><div class="expo-works">${data.works.filter(w=>w.act===act.n).map(w=>work(w,data.works.indexOf(w))).join('\n')}</div></div></section>`).join('\n');
 const intro=`<section class="bg-white"><div class="container"><div class="expo-intro"><span class="eyebrow">L’intention curatoriale</span><h2>Une cour, six œuvres, trois regards</h2><p>Cette exposition numérique relie le fleuve et le souverain, les héritages grecs et le temps de la transmission. Elle prend pour point de départ la restauration de la cour du Sphinx : le Louvre annonce un parcours romain repensé, une nouvelle verrière, la restauration des façades et du sol, ainsi qu’une médiation renouvelée. ${link(project,'Découvrir le projet officiel')}</p><p>Notre sélection réunit des œuvres de dates, de provenances et de fonctions différentes. Une personnification donne un visage à un territoire ; un portrait rend le pouvoir présent ; les reliefs et les mosaïques inscrivent des récits dans l’architecture et les espaces de vie.</p><aside class="expo-note" aria-label="Statut de l’exposition"><p>Proposition éditoriale indépendante de Mecenia, sans partenariat avec le Louvre. Le Tibre, la frise d’Artémis et la Mosaïque des Saisons figurent dans le projet du musée. Tibère, Diane de Versailles et la Vénus d’Arles sont des contrepoints choisis par Mecenia. « Maecenas » est notre proposition, non un nom adopté par le Louvre.</p></aside></div><nav class="expo-index" aria-label="Étapes de l’exposition">${data.acts.map(act=>`<a href="#etape-${act.n}">${act.n}. ${esc(act.title)}</a>`).join('')}<a href="#sources-exposition">Méthode et sources</a></nav></div></section>`;
 const method=`<section class="bg-beige" id="sources-exposition"><div class="container expo-method"><span class="eyebrow">Pour approfondir</span><h2 class="title">Conserver, interpréter, transmettre</h2><p>Ce parcours n’est ni un plan d’accrochage officiel ni une reconstitution antique. Les textes « Le regard de Mecenia » sont des interprétations ; les datations et descriptions s’appuient sur les notices citées. Le projet du Louvre relie les œuvres au bâtiment qui les accueille : étanchéité, ventilation, lumière et médiation font partie des conditions de leur transmission. Soutenir ce chantier ne signifie pas devenir propriétaire des œuvres.</p><h3>Sources et reproductions</h3><ul><li>${link(project,'Louvre — Histoire de la cour, chantier et ensembles annoncés')}</li>${data.works.filter(w=>w.source!==project).map(w=>`<li>${link(w.source,'Louvre — '+w.title)}</li>`).join('')}</ul><p>Les photographies proviennent de Wikimedia Commons : l’auteur, la licence et le fichier d’origine figurent sous chaque image. Les reproductions sont hébergées avec le site, affichées sans recadrage et agrandissables par un clic. Une photographie partielle d’un ensemble n’en restitue pas la totalité.</p><p class="expo-source-date">Parcours d’octobre 2026 · Mise à jour éditoriale : 3 octobre 2026. Les annonces du musée peuvent évoluer ; aucun emplacement futur ni calendrier de déplacement n’est fixé ici.</p></div></section>`;
 const title='Maecenas : réinventer la cour du Sphinx — Exposition | Mecenia',description='Six œuvres antiques, trois étapes et des cartels documentés : une exposition numérique indépendante proposée par Mecenia.',structured={'@context':'https://schema.org','@type':'CollectionPage',name:title,description,url:'https://www.mecenia.org/exposition/',inLanguage:'fr-FR'};
 const html=`<!DOCTYPE html><html lang="fr" class="no-js"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="https://www.mecenia.org/exposition/"><meta name="theme-color" content="#2E2114"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="https://www.mecenia.org/assets/img/exposition/tibre.jpg"><link rel="icon" href="/favicon.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>${styles}${css}<script type="application/ld+json">${JSON.stringify(structured)}</script></head><body><a class="skip" href="#contenu">Aller au contenu</a>${header[0]}<main id="contenu" class="expo-page"><section class="hero small"><div class="container hero-content"><div class="breadcrumb"><a href="/">Accueil</a> / <a href="/blog/">Le blog</a> / L’exposition</div><span class="eyebrow">L’exposition Mecenia · Octobre 2026</span><h1>Maecenas : réinventer la cour du Sphinx</h1><p class="sub">Un territoire, des héritages, le temps de la transmission : six œuvres antiques pour regarder autrement un lieu en devenir.</p><div class="btn-row"><a class="btn" href="#etape-1">Commencer la visite</a><a class="btn-outline" href="/blog/cour-du-sphinx-louvre-tous-mecenes/">Lire notre article</a></div></div></section>${intro}${acts}${method}<section class="bg-dark cta"><div class="container"><h2>La culture se transmet ensemble</h2><p>Cette exposition prolonge le dialogue entre les œuvres, leurs publics et ceux qui soutiennent leur conservation.</p><div class="btn-row"><a class="btn" href="/notre-mission/">Découvrir notre mission</a><a class="btn-outline" href="/contact/">Échanger avec nous</a></div></div></section></main>${footer[0]}<script src="/assets/main.js" defer></script></body></html>`;
 const target=path.join(dist,'exposition/index.html');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,html);
 let changed=0;function visit(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory()){if(entry.name!=='admin')visit(file)}else if(/\.(html|json|txt|xml)$/.test(entry.name)){const old=fs.readFileSync(file,'utf8'),next=clean(old);if(next!==old){fs.writeFileSync(file,next);changed++}}}}visit(dist);
 const sitemap=path.join(dist,'sitemap.xml');if(fs.existsSync(sitemap)){let xml=fs.readFileSync(sitemap,'utf8');if(!/<loc>https:\/\/(?:www\.)?mecenia\.org\/exposition\/<\/loc>/.test(xml)){xml=xml.replace('</urlset>','<url><loc>https://www.mecenia.org/exposition/</loc></url>\n</urlset>');fs.writeFileSync(sitemap,xml)}}
 console.log(`Exposition : 6 images locales, 3 étapes ; statut associatif corrigé dans ${changed} fichier(s).`);
};
