'use strict';
/* Finition éditoriale : newsletter future, consentement indépendant, badges fondateurs. */
const fs = require('fs'), path = require('path');
const OUT = path.join(process.cwd(), 'dist');
const read = p => fs.readFileSync(p, 'utf8');
const write = (p, h) => fs.writeFileSync(p, h);
const consent = '<label class="check newsletter-consent"><input type="checkbox" name="newsletter" value="oui"><span>Je souhaite recevoir par e-mail la future newsletter mensuelle de Mecenia : actualités de l’association, articles, sélection d’expositions et prochains événements. J’accepte l’utilisation de mon adresse e-mail à cette fin, conformément à la <a class="link" href="/mentions-legales/#confidentialite">politique de confidentialité</a>. Je pourrai retirer mon consentement à tout moment.</span></label>';
function patch(relative, changes) {
  const p = path.join(OUT, relative);
  if (!fs.existsSync(p)) return;
  let h = read(p), before = h;
  changes.forEach(([from, to]) => { if (h.includes(from)) h = h.replace(from, to); });
  if (h !== before) write(p, h);
}
patch('equipe/index.html', [
  ['<div class="chips"><span class="chip">Histoire de l’art</span><span class="chip">École du Louvre</span><span class="chip">CNJE</span><span class="chip">Événementiel</span><span class="chip">Médiation culturelle</span></div>', '<div class="chips"><span class="chip">Histoire de l’art</span><span class="chip">École du Louvre</span><span class="chip">Médiation culturelle</span></div>'],
  ['<div class="chips"><span class="chip">Droit</span><span class="chip">Propriété intellectuelle</span><span class="chip">CEIPI</span><span class="chip">CNJE</span><span class="chip">Gouvernance</span></div>', '<div class="chips"><span class="chip">Droit</span><span class="chip">CEIPI</span><span class="chip">Propriété intellectuelle</span></div>']
]);
patch('contact/index.html', [['</label><button class="btn" type="submit">Envoyer</button>', '</label>' + consent + '<button class="btn" type="submit">Envoyer</button>']]);
patch('adherer/index.html', [['</label><button class="btn" type="submit">Envoyer ma demande</button>', '</label>' + consent + '<button class="btn" type="submit">Envoyer ma demande</button>']]);
patch('nos-projets/index.html', [['</article>\n  </div>\n</div></section>\n<section class="bg-white"><div class="container">\n  <span class="eyebrow reveal">Calendrier</span>', '</article>\n    <article class="pcard"><span class="tag">À venir</span><h3>La lettre mensuelle de Mecenia</h3><p class="s">Un rendez-vous pour découvrir nos actualités et notre sélection culturelle.</p><button class="plus-btn" type="button" aria-expanded="false" aria-label="Afficher le détail : La lettre mensuelle de Mecenia"><span class="ico" aria-hidden="true"></span></button><div class="plus-panel"><div><div class="plus-inner"><p>À l’étude : une newsletter mensuelle réunissant les nouveautés de Mecenia, les articles publiés dans le mois, une sélection d’expositions à découvrir et nos prochains événements. Son lancement et son calendrier seront annoncés ultérieurement. L’inscription sera facultative.</p></div></div></div></article>\n  </div>\n</div></section>\n<section class="bg-white"><div class="container">\n  <span class="eyebrow reveal">Calendrier</span>']]);
patch('mentions-legales/index.html', [['<p>Les données collectées via les formulaires (identité, coordonnées, fonction, message) sont utilisées aux seules fins de répondre à votre demande, de gérer la vie associative, d’organiser les événements et de communiquer sur les activités de Mecenia. Elles ne sont ni cédées ni louées à des tiers sans votre consentement exprès.</p>', '<p>Les données collectées via les formulaires (identité, coordonnées, fonction, message) sont utilisées aux seules fins de répondre à votre demande, de gérer la vie associative, d’organiser les événements et de communiquer sur les activités de Mecenia. Elles ne sont ni cédées ni louées à des tiers sans votre consentement exprès.</p><h3>Future newsletter de Mecenia</h3><p>Si vous cochez la case facultative dédiée, votre adresse e-mail est collectée sur la base de votre consentement afin de préparer, puis de vous adresser, la future newsletter mensuelle de Mecenia : actualités de l’association, articles, sélection d’expositions et prochains événements. Ce choix est indépendant de votre demande de contact ou d’adhésion et son refus n’a aucune conséquence sur celle-ci.</p><p>Les données liées à cet abonnement (adresse e-mail, date, formulaire d’origine et version du texte de consentement) sont accessibles aux seules personnes habilitées de Mecenia. Lorsqu’un prestataire d’envoi sera retenu, il agira pour le compte de Mecenia afin de diffuser la newsletter. Les adresses ne seront ni vendues ni louées.</p><p>Avant le lancement effectif de la newsletter, les données de préinscription seront conservées pendant trois ans au maximum à compter de leur collecte. Après son lancement, elles seront conservées pendant la durée de votre abonnement, jusqu’au retrait de votre consentement. Vous pourrez vous désinscrire à tout moment en écrivant à <a href="mailto:contact@mecenia.org">contact@mecenia.org</a>, puis grâce au lien de désinscription présent dans chaque envoi.</p>']]);
console.log('Newsletter : présentation, consentement et confidentialité mis à jour.');
