"use strict";
/* Ressources generales : aucun document interne publie, aucune annonce de programme. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const OUT=path.join(process.cwd(),'dist'),BASE='https://www.mecenia.org';
const read=p=>fs.readFileSync(path.join(OUT,p),'utf8');
const put=(p,h)=>{const f=path.join(OUT,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,h)};
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const main=h=>(h.match(/<main\b[^>]*>[\s\S]*?<\/main>/)||[''])[0];
const protectedFiles=['a-propos/index.html','aide-au-mecenat/index.html','evenements/index.html','contact/index.html','blog/index.html'];
const before=Object.fromEntries(protectedFiles.map(f=>[f,main(read(f))]));
const template=read('a-propos/index.html');
const body=`<section class="hero small"><div class="container hero-content"><div class="breadcrumb rise"><a href="/">Accueil</a> &nbsp;/&nbsp; Ressources</div><h1 class="rise d1">Ressources</h1><p class="sub rise d2">Comprendre avec rigueur, partager avec responsabilité.</p><div class="btn-row rise d3"><a class="btn" href="/blog/">Lire nos articles</a></div></div></section>
<section class="bg-white" id="articles"><div class="container narrow"><div class="prose reveal"><span class="eyebrow" style="text-align:left">Les contenus accessibles</span><h2>Nos articles, un point d’entrée dans les enjeux</h2><p>Mecenia fait dialoguer les regards culturels, économiques et juridiques. Les articles publiés sur le blog permettent d’explorer les projets, le patrimoine et les principes du mécénat, avec leurs sources et leurs limites.</p><p>Pour le moment, cette rubrique oriente vers ces articles. Elle ne propose pas de livre blanc, de rapport à télécharger ou de programme de formation ouvert à l’inscription.</p><p><a class="arrow-link" href="/blog/">Consulter le blog de Mecenia</a></p></div></div></section>
<section class="bg-beige" id="formats"><div class="container"><span class="eyebrow reveal">Les formats de la transmission</span><h2 class="title reveal">Des supports adaptés aux usages</h2><p class="lead reveal">Ces formats sont présentés de manière générale. Ils ne constituent pas l’annonce d’une publication, d’un calendrier ou d’un programme disponible.</p><div class="grid g3 stagger"><article class="card"><h3>Formations et sensibilisation</h3><p>Transmettre des repères suppose de les adapter aux publics et à leurs besoins. Un contenu pédagogique doit distinguer les notions générales, les exemples et les situations qui nécessitent un accompagnement particulier.</p></article><article class="card"><h3>Notes, rapports et livres blancs</h3><p>Une analyse utile explicite son périmètre, ses sources et sa méthode. Les constats doivent être distingués des propositions, et les limites du travail rendues lisibles.</p></article><article class="card"><h3>Outils pédagogiques</h3><p>Un support pratique ou ludique peut faciliter la compréhension. Il doit rester fidèle au sujet, respecter les droits des créateurs et éviter de transformer une simplification en certitude.</p></article></div></div></section>
<section class="bg-white" id="principes"><div class="container"><span class="eyebrow reveal">Notre ligne éditoriale</span><h2 class="title reveal">Une information que l’on peut situer et vérifier</h2><div class="grid g2 stagger"><article class="card"><h3>Sourcer et dater</h3><p>Identifier les références, préciser la période concernée et distinguer une donnée observée d’un objectif, d’un projet ou d’une estimation.</p></article><article class="card"><h3>Expliquer les limites</h3><p>Ne pas présenter une opinion comme un fait, une comparaison comme une preuve ou un exemple comme une règle universelle. Signaler les incertitudes et les différences de périmètre.</p></article><article class="card"><h3>Respecter les auteurs</h3><p>Accorder une attention aux droits, aux crédits et aux conditions de réutilisation des textes, des images et des données. Le partage n’efface pas la création qui le rend possible.</p></article><article class="card"><h3>Préserver l’indépendance</h3><p>Garder une lecture critique, distinguer l’information de la promotion et rendre compréhensible le contexte dans lequel un contenu est produit.</p></article></div></div></section>
<section class="bg-beige" id="limites"><div class="container narrow"><div class="prose reveal"><span class="eyebrow" style="text-align:left">Un cadre clair</span><h2>Éclairer, sans se substituer à un conseil personnalisé</h2><p>Les contenus de Mecenia ont une vocation informative et pédagogique. Ils ne remplacent pas l’examen d’une situation individuelle par un professionnel compétent et, lorsque cela est requis, habilité.</p><p>La lecture d’un article ou d’un support ne garantit ni l’éligibilité fiscale d’un don, ni l’obtention d’une subvention, ni la réussite d’une recherche de financement.</p></div></div></section>
<section class="bg-dark cta"><div class="container reveal"><h2>Une question, un sujet ou une correction à proposer ?</h2><p>Le dialogue contribue à la qualité des contenus. Écrivez-nous pour partager une remarque ou un besoin de compréhension.</p><a class="btn" href="/contact/">Écrire à Mecenia</a></div></section>`;
let h=template;const title='Ressources — Culture, économie et mécénat | Mecenia',description='Les articles et les principes éditoriaux de Mecenia : sources, transparence, respect des auteurs et information générale sur la culture et le mécénat.';
h=h.replace(/<main\b[^>]*>[\s\S]*?<\/main>/,()=>'<main id="contenu">'+body+'</main>').replace(/<title>[\s\S]*?<\/title>/,()=>'<title>'+esc(title)+'</title>').replace(/<link rel="canonical" href="[^"]*"[^>]*>/,()=>'<link rel="canonical" href="'+BASE+'/ressources/">');
h=h.replace(/<meta\b[^>]*(?:name|property)="(description|og:title|og:description|og:url|twitter:title|twitter:description)"[^>]*>/g,(_,k)=>'<meta '+(k.startsWith('og:')?'property':'name')+'="'+k+'" content="'+esc(k.endsWith('title')?title:k==='og:url'?BASE+'/ressources/':description)+'">');
const ld={'@context':'https://schema.org','@graph':[{'@type':'NGO','@id':BASE+'/#organization',name:'Mecenia',url:BASE+'/'},{'@type':'WebPage',url:BASE+'/ressources/',name:title,description,inLanguage:'fr-FR'}]};
h=h.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/g,()=>'<script type="application/ld+json">'+JSON.stringify(ld).replace(/</g,'\u003c')+'</script>');put('ressources/index.html',h);
function addLink(block){if(block.includes('href="/ressources/"'))return block;return block.replace(/(<li\b[^>]*>\s*<a\b[^>]*href="\/evenements\/"[^>]*>[\s\S]*?<\/a>\s*<\/li>)/,'$1<li><a href="/ressources/">Ressources</a></li>')}
function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory()){if(!['admin','assets','netlify'].includes(e.name))walk(f)}else if(e.name.endsWith('.html')){let s=fs.readFileSync(f,'utf8');s=s.replace(/<nav\b[^>]*>[\s\S]*?<\/nav>/g,addLink).replace(/<footer\b[^>]*>[\s\S]*?<\/footer>/g,addLink);fs.writeFileSync(f,s)}}}walk(OUT);
for(const f of protectedFiles)assert(main(read(f))===before[f],'Contenu modifié : '+f);
const result=read('ressources/index.html'),ids=[...result.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert(ids.length===new Set(ids).size,'Identifiants dupliqués sur Ressources');assert(result.includes('href="/ressources/"'),'Lien de navigation absent');
for(const id of ['articles','formats','principes','limites'])assert(ids.includes(id),'Section absente : '+id);
const sm=path.join(OUT,'sitemap.xml');if(fs.existsSync(sm)){let s=fs.readFileSync(sm,'utf8');if(!s.includes('<loc>'+BASE+'/ressources/</loc>'))s=s.replace('</urlset>','<url><loc>'+BASE+'/ressources/</loc><lastmod>2026-10-08</lastmod></url>\n</urlset>');fs.writeFileSync(sm,s)}
const lm=path.join(OUT,'llms.txt');if(fs.existsSync(lm)){let s=fs.readFileSync(lm,'utf8');if(!s.includes(BASE+'/ressources/'))s+='\n- [Ressources]('+BASE+'/ressources/) : articles et principes de transmission, sans annonce de publication ou de programme particulier.\n';fs.writeFileSync(lm,s)}
console.log('Ressources : page générale ajoutée, aucun nouveau document publié, contenus existants conservés.');
